### ISSUE TITLE
Wont prcess any files

### ISSUE THREAD

**Issue by MelvinMik** [whatmakeart/batch-bake-render#1]
It's just stuck at 0 frames and wont bake. I'm using blender 4.2.2 which version is compatible with this can u pls update it?

**Comment by whatmakeart** [comment]
Updated to work with Blender 4.2 here https://github.com/whatmakeart/eevee-batch-bake-lighting/releases/tag/v1.0.0 Let me know if it works for you.

**Comment by whatmakeart** [comment]
Updated to work with Blender 4.2 here https://github.com/whatmakeart/eevee-batch-bake-lighting/releases/tag/v1.0.0 let me know if it works.
